name: Vercel Preview Deploment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

        # 1. Install your dependencies (so Prisma & your code are present)
      - name: Install dependencies
        run: npm ci

      # 2. Generate Prisma Client (will build both Debian & RHEL engines)
      - name: Generate Prisma Client
        run: npx prisma generate

      - name: install Vercel CLI
        run: npm install --global vercel@latest

      - name: pull Vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: build project artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: deploy project artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
